import{a as M,S as $,i as y}from"./assets/vendor-0Fq3u7cb.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const l of o.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&a(l)}).observe(document,{childList:!0,subtree:!0});function e(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(t){if(t.ep)return;t.ep=!0;const o=e(t);fetch(t.href,o)}})();const P="https://pixabay.com/api/";async function g(r,s=1,e=15){const a=new URLSearchParams({key:"",q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:e,page:s});return(await M.get(`${P}?${a}`)).data}const x=document.querySelector(".gallery");function L(r){const s=r.hits.map(e=>`
          <div class="image-card">
              <a href="${e.largeImageURL}" class="link">
                  <img src="${e.webformatURL}" alt="${e.tags}" width=640 height=360>
              </a>
              <div class="info">
                  <p><span>Likes</span> ${e.likes}</p>
                  <p><span>Views</span> ${e.views}</p>
                  <p><span>Comments</span> ${e.comments}</p>
                  <p><span>Downloads</span> ${e.downloads}</p>
              </div>
          </div>
      `).join("");x.insertAdjacentHTML("beforeend",s)}const m=document.querySelector(".gallery"),C=document.querySelector(".search-form"),p=document.querySelector(".load-more-btn"),v=document.querySelector(".loader"),w=new $(".gallery a"),d=15;let n=1,h=0,u=0,i="";function b(){v.classList.add("is-active")}function S(){v.classList.remove("is-active")}function c(){p.classList.add("is-hidden")}function E(){p.classList.remove("is-hidden")}c();C.addEventListener("submit",I);async function I(r){r.preventDefault(),m.innerHTML="",b();const s=r.currentTarget;i=s.elements.query.value.trim().toLowerCase();try{n=1;const e=await g(i,n,d);if(h=e.totalHits,u=Math.ceil(h/d),i===""||e.hits.length===0){f(),c();return}L(e),w.refresh(),n<u?E():(c(),q())}catch{f()}finally{s.reset(),S()}}p.addEventListener("click",O);async function O(){n+=1,b();try{const r=await g(i,n,d);L(r),w.refresh(),R(),n>=u&&(c(),q())}catch{f()}finally{S()}}function f(r){m.innerHTML="",y.error({maxWidth:500,timeout:3e3,position:"topRight",icon:"material-icons",title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"})}function q(){y.info({maxWidth:500,timeout:3e3,position:"bottomCenter",icon:"material-icons",title:"Info",message:"We're sorry, but you've reached the end of search results"})}function R(){const{height:r}=m.firstElementChild.getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"})}
//# sourceMappingURL=commonHelpers.js.map
